"""
Django settings for DoorstepDine project.
Generated by 'django-admin startproject' using Django 5.1.2.
For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
import os
STRIPE_TEST_PUBLISHABLE_KEY='pk_test_51QFIvpGm5dQPAHUkuvuD1uxHDoPRcLCqohWJh9NtVitufXmP0lX3QHRPYzJZt616Lpczo8dy2KvbiXlbOcr4v2v000q86V6qcA'
STRIPE_TEST_SECRET_KEY='sk_test_51QFIvpGm5dQPAHUkEA9Ci4098KTKgj5A9W1tnBdu0HiqI8ZU6OvB26D9uINWq4zvzFa43XCAYE4uv1MhK7ewEAZa00rskqxY8z'
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-s)=lb-uu9eqw2m1t(!*&zzw%!#+s86g8ks@!8=_k%4i5@_5wwz'
DEBUG = True
ALLOWED_HOSTS = []
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
    'tailwind',
    'theme',
    'post_office',
]
ASGI_APPLICATION = 'DoorstepDine.asgi.application' 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'dhamijasurvesh@gmail.com'
EMAIL_HOST_PASSWORD = 'omgq hfkj hcpi cnah'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'dhamijasurvesh@gmail.com'
TAILWIND_APP_NAME='theme'
INTERNAL_IPS = ['127.0.0.1']
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'DoorstepDine.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'DoorstepDine.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'temp1',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'Kush@2005',
        'PORT': '3306',
    }
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
import sentry_sdk

sentry_sdk.init(
    dsn="https://10dfdca8068fba1115b2e3193d8260f9@o4508240740876288.ingest.us.sentry.io/4508240743366656",
   
    traces_sample_rate=1.0,
    _experiments={
        "continuous_profiling_auto_start": True,
    },
)
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
AUTH_USER_MODEL = 'App.Customer'
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL='/media/'
MEDIA_ROOT= os.path.join(BASE_DIR, 'media')
STATIC_URL='static/'
STATIC_ROOT= [os.path.join(BASE_DIR, 'static')]
